### ISSUE TITLE
Resetting control signals with the VK sets them to 0 instead of 64

### ISSUE THREAD

**Issue by jplloyd** [Yoshimi/yoshimi#113]
Right-clicking the control slider on the right side of the virtual keyboard centers the visual as usual, but the value is actually set to 0.

Not working as intended in e1a01c26e531da21558fd18a62054d2b780a023d, and it's been that way for well over a year (not sure exactly when, the xml change makes it a bit of a pain to bisect).

**Comment by abrolag** [comment]
Just god back form a zero tech break :)
Did a quick check and confirm. However, it seems the ranges of that control are quite broken anyway. This probably goes back to when the control was no longer applied directly with a mutex lock, but routed through MIDI instead.

**Comment by abrolag** [comment]
This was in fact due to the limits testing not recognising MIDI CC defaults, so setting a 'safe' value of zero. I've now trapped this and (for now) let the value pass through untested.

It also highlights the virtual keyboard has *never* set a correct default value when changing the CC that slider controls.
e.g. Expression should default to maximum.

Another one for the TODO list :(

**Comment by abrolag** [comment]
This completely revised now. I've added two new dynamic tooltips. VC_plainReverse & VC_pitchWheel. I think I've got this right - leastways the seem to work!
