### ISSUE TITLE
SCL tuning file import not working

### ISSUE THREAD

**Issue by y6nH** [Yoshimi/yoshimi#115]
I'm running Yoshimi 1.7.2 on Manjaro 20.1.

I've downloaded the SCL file collection from http://www.huygens-fokker.org/scala/scl_format.html. When I try to import one of the tunings in Yoshimi (Scales > Show Settings, click "Import .scl file"), it fails, with the message "Tuning: Empty file".

If I paste the numeric lines of the same tuning file into the Yoshimi window, it works as expected. 

The button worked fine previously, but I'm not sure what version of Yoshimi that was.

**Comment by abrolag** [comment]
On Sun, 25 Oct 2020 03:58:08 -0700
Hugh <notifications@github.com> wrote:

>I'm running Yoshimi 1.7.2 on Manjaro 20.1.
>
>I've downloaded the SCL file collection from http://www.huygens-fokker.org/scala/scl_format.html. When I try to import one of the tunings in Yoshimi (Scales > Show Settings, click "Import .scl file"), it fails, with the message "Tuning: Empty file".
>
>If I paste the numeric lines of the same tuning file into the Yoshimi window, it works as expected. 
>
>The button worked fine previously, but I'm not sure what version of Yoshimi that was.
>

I can confirm that here and it goes back at least to V 1.5.10. It took a while
to find the problem :(

Some time back we got more aggressive adhering to the Scala spec. only failed
to realise that Microsoft sourced files would create alternate blank lines in a
Unix style reader. These are not allowed!

Fixed in the latest commit (if you can self-build). We'll probably push out a
minor release soon.

Will.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by y6nH** [comment]
Thanks for the quick response! I'll work around it with copy and paste for now, and wait for the fix to hit the repos.
